package com.orderprocessing.order.event;

public enum OrderEventType {
    ORDER_CREATED,
    ORDER_INVENTORY_RESERVED,
    ORDER_INVENTORY_FAILED,
    ORDER_PAYMENT_PROCESSING,
    ORDER_PAYMENT_COMPLETED,
    ORDER_PAYMENT_FAILED,
    ORDER_COMPLETED,
    ORDER_CANCELLED,
    ORDER_COMPENSATION_STARTED
}